version: "2"

services:
    vistool:
        build:
            context: .
            dockerfile: Dockerfile.v2p7
        image: oco2_modis_vistool_v2p7
        container_name: oco2_modis_vistool_v2p7
        volumes:
        - ./:/code/
        tty: true
        network_mode: bridge
